import { Demo, KioskSettings } from '../models';

export const SEED_DEMOS: Demo[] = [
  {
    id: 'demo-speech-1',
    title: 'Speech-to-Text Live Transcription',
    description: 'Real-time transcription of spoken language using Azure AI Speech services.',
    demoUrl: 'https://speech.example.com/transcription',
    thumbnailUrl: '/thumbnails/speech.png',
    tags: ['Speech', 'Transcription', 'Azure AI'],
    launchMode: 'sameTab',
    isActive: true,
    sortOrder: 1,
    owner: 'demo-team@microsoft.com',
  },
  {
    id: 'demo-vision-1',
    title: 'Computer Vision Object Detection',
    description: 'Detect and classify objects in images using Azure Computer Vision.',
    demoUrl: 'https://vision.example.com/detection',
    thumbnailUrl: '/thumbnails/vision.png',
    tags: ['Vision', 'Object Detection', 'Azure AI'],
    launchMode: 'sameTab',
    isActive: true,
    sortOrder: 2,
    owner: 'demo-team@microsoft.com',
  },
  {
    id: 'demo-language-1',
    title: 'Language Understanding & Sentiment',
    description: 'Analyze text for sentiment, key phrases, and language understanding.',
    demoUrl: 'https://language.example.com/sentiment',
    thumbnailUrl: '/thumbnails/language.png',
    tags: ['Language', 'Sentiment Analysis', 'Azure AI'],
    launchMode: 'sameTab',
    isActive: true,
    sortOrder: 3,
    owner: 'demo-team@microsoft.com',
  },
  {
    id: 'demo-decision-1',
    title: 'Anomaly Detection Dashboard',
    description: 'Detect anomalies in time-series data using AI-powered decision services.',
    demoUrl: 'https://decision.example.com/anomaly',
    thumbnailUrl: '/thumbnails/decision.png',
    tags: ['Decision', 'Anomaly Detection', 'Azure AI'],
    launchMode: 'sameTab',
    isActive: true,
    sortOrder: 4,
    owner: 'demo-team@microsoft.com',
  },
  {
    id: 'demo-agentic-1',
    title: 'Agentic AI Workflow Orchestrator',
    description: 'Autonomous AI agents collaborating to complete complex multi-step tasks.',
    demoUrl: 'https://agentic.example.com/workflow',
    thumbnailUrl: '/thumbnails/agentic.png',
    tags: ['Agentic', 'Workflow', 'Azure AI'],
    launchMode: 'sameTab',
    isActive: true,
    sortOrder: 5,
    owner: 'demo-team@microsoft.com',
  },
];

export const DEFAULT_SETTINGS: KioskSettings = {
  idleTimeoutSeconds: 60,
  featuredDemoIds: [],
};
